name: SimpleTeleport
version: 1.0.0
main: com.notjunar.simpleteleport.SimpleTeleport
api-version: 1.13
author: notjunar
description: A simple teleportation plugin with home, spawn, warp, and TPA functionality.

commands:
  home:
    description: Teleport to your home or set your home location
    usage: /<command> [set]
  spawn:
    description: Teleport to the server spawn or set the spawn location
    usage: /<command> [set]
  warp:
    description: Teleport to a warp or set a new warp
    usage: /<command> <name> [set]
  tpa:
    description: Send a teleport request to another player
    usage: /<command> <player>
  tpahere:
    description: Request another player to teleport to you
    usage: /<command> <player>
  tpaccept:
    description: Accept a pending teleport request
    usage: /<command>
  tpdeny:
    description: Deny a pending teleport request
    usage: /<command>

permissions:
  simpleteleport.*:
    description: Gives access to all SimpleTeleport commands
    children:
      simpleteleport.home: true
      simpleteleport.spawn: true
      simpleteleport.warp: true
      simpleteleport.tpa: true
      simpleteleport.admin: true
  simpleteleport.home:
    description: Allows use of /home command
    default: true
  simpleteleport.spawn:
    description: Allows use of /spawn command
    default: true
  simpleteleport.warp:
    description: Allows use of /warp command
    default: true
  simpleteleport.tpa:
    description: Allows use of /tpa, /tpahere, /tpaccept, and /tpdeny commands
    default: true
  simpleteleport.admin:
    description: Allows use of admin functions like setting spawn and warps
    default: op